# Generated by Django 5.1.6 on 2025-03-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_order_paymentrequest_alter_product_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=225, verbose_name='Пользователь')),
                ('product', models.CharField(max_length=225, verbose_name='Продукт')),
                ('quantity', models.PositiveSmallIntegerField(verbose_name='Количество')),
                ('check_image', models.ImageField(upload_to='media/check', verbose_name='Чек')),
            ],
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='total_price',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
