# Generated by Django 5.1.6 on 2025-03-13 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_otp_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
